# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `colored2` gem.
# Please instead update this file by running `bin/tapioca gem colored2`.

# source://colored2//lib/colored2/codes.rb#3
module Colored2
  class << self
    # source://colored2//lib/colored2/ascii_decorator.rb#15
    def background_next!; end

    # @return [Boolean]
    #
    # source://colored2//lib/colored2/ascii_decorator.rb#23
    def background_next?; end

    # source://colored2//lib/colored2.rb#7
    def decorate(a_class); end

    # source://colored2//lib/colored2/ascii_decorator.rb#11
    def disable!; end

    # source://colored2//lib/colored2/ascii_decorator.rb#7
    def enable!; end

    # source://colored2//lib/colored2/ascii_decorator.rb#19
    def foreground_next!; end

    # @private
    #
    # source://colored2//lib/colored2.rb#11
    def included(from_class); end
  end
end

# source://colored2//lib/colored2/ascii_decorator.rb#27
class Colored2::AsciiDecorator
  extend ::Forwardable

  # @return [AsciiDecorator] a new instance of AsciiDecorator
  #
  # source://colored2//lib/colored2/ascii_decorator.rb#63
  def initialize(a_string); end

  # options[:start] = :color
  # options[:end]   = :color | :no_color
  #
  # source://colored2//lib/colored2/ascii_decorator.rb#70
  def decorate(options = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def disable!(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def enable!(*args, **_arg1, &block); end

  # Returns the value of attribute my_class.
  #
  # source://colored2//lib/colored2/ascii_decorator.rb#61
  def my_class; end

  # Sets the attribute my_class
  #
  # @param value the value to set the attribute my_class to.
  #
  # source://colored2//lib/colored2/ascii_decorator.rb#61
  def my_class=(_arg0); end

  # Returns the value of attribute string.
  #
  # source://colored2//lib/colored2/ascii_decorator.rb#61
  def string; end

  # Sets the attribute string
  #
  # @param value the value to set the attribute string to.
  #
  # source://colored2//lib/colored2/ascii_decorator.rb#61
  def string=(_arg0); end

  # source://colored2//lib/colored2/ascii_decorator.rb#89
  def un_decorate; end

  private

  # source://colored2//lib/colored2/ascii_decorator.rb#95
  def no_color; end

  class << self
    # Returns the value of attribute __background_next.
    #
    # source://colored2//lib/colored2/ascii_decorator.rb#31
    def __background_next; end

    # Sets the attribute __background_next
    #
    # @param value the value to set the attribute __background_next to.
    #
    # source://colored2//lib/colored2/ascii_decorator.rb#31
    def __background_next=(_arg0); end

    # Returns the value of attribute __colors_disabled.
    #
    # source://colored2//lib/colored2/ascii_decorator.rb#31
    def __colors_disabled; end

    # Sets the attribute __colors_disabled
    #
    # @param value the value to set the attribute __colors_disabled to.
    #
    # source://colored2//lib/colored2/ascii_decorator.rb#31
    def __colors_disabled=(_arg0); end

    # source://colored2//lib/colored2/ascii_decorator.rb#45
    def background_next!; end

    # @return [Boolean]
    #
    # source://colored2//lib/colored2/ascii_decorator.rb#53
    def background_next?; end

    # source://colored2//lib/colored2/ascii_decorator.rb#41
    def disable!; end

    # source://colored2//lib/colored2/ascii_decorator.rb#33
    def enable!; end

    # @return [Boolean]
    #
    # source://colored2//lib/colored2/ascii_decorator.rb#37
    def enabled?; end

    # source://colored2//lib/colored2/ascii_decorator.rb#49
    def foreground_next!; end
  end
end

# source://colored2//lib/colored2/codes.rb#60
class Colored2::BackgroundColor < ::Colored2::TextColor
  # source://colored2//lib/colored2/codes.rb#61
  def value; end
end

# source://colored2//lib/colored2/codes.rb#4
Colored2::COLORS = T.let(T.unsafe(nil), Hash)

# source://colored2//lib/colored2/codes.rb#26
class Colored2::Code
  # @raise [ArgumentError]
  # @return [Code] a new instance of Code
  #
  # source://colored2//lib/colored2/codes.rb#29
  def initialize(name); end

  # Returns the value of attribute escape.
  #
  # source://colored2//lib/colored2/codes.rb#27
  def escape; end

  # Sets the attribute escape
  #
  # @param value the value to set the attribute escape to.
  #
  # source://colored2//lib/colored2/codes.rb#27
  def escape=(_arg0); end

  # Returns the value of attribute name.
  #
  # source://colored2//lib/colored2/codes.rb#27
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # source://colored2//lib/colored2/codes.rb#27
  def name=(_arg0); end

  # source://colored2//lib/colored2/codes.rb#43
  def to_s; end

  # source://colored2//lib/colored2/codes.rb#37
  def value(shift = T.unsafe(nil)); end
end

# source://colored2//lib/colored2/codes.rb#15
Colored2::EFFECTS = T.let(T.unsafe(nil), Hash)

# source://colored2//lib/colored2/codes.rb#48
class Colored2::Effect < ::Colored2::Code
  # source://colored2//lib/colored2/codes.rb#49
  def codes; end
end

# source://colored2//lib/colored2/codes.rb#54
class Colored2::TextColor < ::Colored2::Code
  # source://colored2//lib/colored2/codes.rb#55
  def codes; end
end

class String
  include ::Comparable
  include ::Colored2
end
