# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `cppjieba_rb` gem.
# Please instead update this file by running `bin/tapioca gem cppjieba_rb`.

# source://cppjieba_rb//lib/cppjieba_rb/version.rb#1
module CppjiebaRb
  class << self
    # source://cppjieba_rb//lib/cppjieba_rb.rb#13
    def extract_keyword(str, top_n); end

    # source://cppjieba_rb//lib/cppjieba_rb.rb#25
    def filter_stop_word(arr); end

    # source://cppjieba_rb//lib/cppjieba_rb.rb#30
    def internal; end

    # source://cppjieba_rb//lib/cppjieba_rb.rb#17
    def segment(str, opts = T.unsafe(nil)); end

    # source://cppjieba_rb//lib/cppjieba_rb.rb#21
    def segment_tag(str); end
  end
end

# source://cppjieba_rb//lib/cppjieba_rb.rb#7
CppjiebaRb::DICT_PATH = T.let(T.unsafe(nil), String)

# source://cppjieba_rb//lib/cppjieba_rb.rb#6
CppjiebaRb::EXT_BASE = T.let(T.unsafe(nil), String)

# source://cppjieba_rb//lib/cppjieba_rb.rb#8
CppjiebaRb::HMM_DICT_PATH = T.let(T.unsafe(nil), String)

# source://cppjieba_rb//lib/cppjieba_rb.rb#10
CppjiebaRb::IDF_PATH = T.let(T.unsafe(nil), String)

class CppjiebaRb::Internal
  def initialize(_arg0, _arg1, _arg2, _arg3, _arg4); end

  def extract_keyword(_arg0, _arg1); end
  def segment(_arg0, _arg1, _arg2, _arg3); end
  def segment_tag(_arg0); end
  def stop_word?(_arg0); end
end

# source://cppjieba_rb//lib/cppjieba_rb.rb#11
CppjiebaRb::STOP_WORD_PATH = T.let(T.unsafe(nil), String)

# source://cppjieba_rb//lib/cppjieba_rb/segment.rb#2
class CppjiebaRb::Segment
  # @return [Segment] a new instance of Segment
  #
  # source://cppjieba_rb//lib/cppjieba_rb/segment.rb#5
  def initialize(opts = T.unsafe(nil)); end

  # source://cppjieba_rb//lib/cppjieba_rb/segment.rb#16
  def segment(str); end
end

# source://cppjieba_rb//lib/cppjieba_rb/segment.rb#3
CppjiebaRb::Segment::VALID_MODES = T.let(T.unsafe(nil), Array)

# source://cppjieba_rb//lib/cppjieba_rb.rb#9
CppjiebaRb::USER_DICT = T.let(T.unsafe(nil), String)

# source://cppjieba_rb//lib/cppjieba_rb/version.rb#2
CppjiebaRb::VERSION = T.let(T.unsafe(nil), String)
