# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `discourse_dev_assets` gem.
# Please instead update this file by running `bin/tapioca gem discourse_dev_assets`.

# source://discourse_dev_assets//lib/discourse_dev_assets/engine.rb#3
module DiscourseDevAssets
  class << self
    # source://discourse_dev_assets//lib/discourse_dev_assets.rb#8
    def avatars; end
  end
end

# source://discourse_dev_assets//lib/discourse_dev_assets/engine.rb#4
class DiscourseDevAssets::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.0.7/lib/active_support/callbacks.rb#68
    def __callbacks; end
  end
end

# source://discourse_dev_assets//lib/discourse_dev_assets/version.rb#4
DiscourseDevAssets::VERSION = T.let(T.unsafe(nil), String)

# source://discourse_dev_assets//lib/discourse_dev_assets.rb#52
NOT_GIVEN = T.let(T.unsafe(nil), Object)
