# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `image_size` gem.
# Please instead update this file by running `bin/tapioca gem image_size`.

# Determine image format and size
#
# source://image_size//lib/image_size/format_error.rb#3
class ImageSize
  # Given image as any class responding to read and eof? or data as String, finds its format and dimensions
  #
  # @return [ImageSize] a new instance of ImageSize
  #
  # source://image_size//lib/image_size.rb#49
  def initialize(data); end

  # Image format
  #
  # source://image_size//lib/image_size.rb#57
  def format; end

  # Image height
  #
  # source://image_size//lib/image_size.rb#64
  def h; end

  # Image height
  #
  # source://image_size//lib/image_size.rb#64
  def height; end

  # get image width and height as an array which to_s method returns "#{width}x#{height}"
  #
  # source://image_size//lib/image_size.rb#68
  def size; end

  # Image width
  #
  # source://image_size//lib/image_size.rb#60
  def w; end

  # Image width
  #
  # source://image_size//lib/image_size.rb#60
  def width; end

  private

  # source://image_size//lib/image_size.rb#76
  def detect_format(ir); end

  # source://image_size//lib/image_size.rb#126
  def detect_jpeg2000_type(ir); end

  # source://image_size//lib/image_size.rb#104
  def detect_png_type(ir); end

  # source://image_size//lib/image_size.rb#117
  def detect_pnm_type(ir); end

  # source://image_size//lib/image_size.rb#149
  def size_of_apng(ir); end

  # source://image_size//lib/image_size.rb#377
  def size_of_avif(ir); end

  # source://image_size//lib/image_size.rb#183
  def size_of_bmp(ir); end

  # source://image_size//lib/image_size.rb#323
  def size_of_cur(ir); end

  # source://image_size//lib/image_size.rb#359
  def size_of_emf(ir); end

  # source://image_size//lib/image_size.rb#137
  def size_of_gif(ir); end

  # source://image_size//lib/image_size.rb#377
  def size_of_heic(ir); end

  # source://image_size//lib/image_size.rb#377
  def size_of_heif(ir); end

  # source://image_size//lib/image_size.rb#323
  def size_of_ico(ir); end

  # source://image_size//lib/image_size.rb#352
  def size_of_j2c(ir); end

  # source://image_size//lib/image_size.rb#345
  def size_of_jp2(ir); end

  # source://image_size//lib/image_size.rb#164
  def size_of_jpeg(ir); end

  # source://image_size//lib/image_size.rb#345
  def size_of_jpx(ir); end

  # source://image_size//lib/image_size.rb#141
  def size_of_mng(ir); end

  # source://image_size//lib/image_size.rb#207
  def size_of_pam(ir); end

  # source://image_size//lib/image_size.rb#198
  def size_of_pbm(ir); end

  # source://image_size//lib/image_size.rb#286
  def size_of_pcx(ir); end

  # source://image_size//lib/image_size.rb#198
  def size_of_pgm(ir); end

  # source://image_size//lib/image_size.rb#149
  def size_of_png(ir); end

  # source://image_size//lib/image_size.rb#198
  def size_of_ppm(ir); end

  # source://image_size//lib/image_size.rb#251
  def size_of_psd(ir); end

  # source://image_size//lib/image_size.rb#300
  def size_of_svg(ir); end

  # source://image_size//lib/image_size.rb#291
  def size_of_swf(ir); end

  # source://image_size//lib/image_size.rb#255
  def size_of_tiff(ir); end

  # source://image_size//lib/image_size.rb#328
  def size_of_webp(ir); end

  # source://image_size//lib/image_size.rb#234
  def size_of_xbm(ir); end

  # source://image_size//lib/image_size.rb#239
  def size_of_xpm(ir); end

  class << self
    # Used for svg
    #
    # source://image_size//lib/image_size.rb#39
    def dpi; end

    # Used for svg
    #
    # source://image_size//lib/image_size.rb#44
    def dpi=(dpi); end

    # Given path to image finds its format, width and height
    #
    # source://image_size//lib/image_size.rb#34
    def path(path); end
  end
end

# source://image_size//lib/image_size/chunky_reader.rb#6
module ImageSize::ChunkyReader
  include ::ImageSize::Reader

  # Including class should define method chunk that accepts the chunk number
  # and returns a string of chunk_size length or shorter for last chunk, or
  # nil for further chunks.
  # Determines required chunks, takes parts of them to construct desired
  # substring, behaves same as str[start, length] except start can't be
  # negative.
  #
  # @raise [ArgumentError]
  #
  # source://image_size//lib/image_size/chunky_reader.rb#20
  def [](offset, length); end

  # Size of a chunk in which to read
  #
  # source://image_size//lib/image_size/chunky_reader.rb#10
  def chunk_size; end
end

# source://image_size//lib/image_size.rb#357
ImageSize::EMF_SMAX = T.let(T.unsafe(nil), Integer)

# source://image_size//lib/image_size.rb#356
ImageSize::EMF_UMAX = T.let(T.unsafe(nil), Integer)

# source://image_size//lib/image_size/format_error.rb#4
class ImageSize::FormatError < ::StandardError; end

# source://image_size//lib/image_size.rb#372
ImageSize::HEIF_WALKER = T.let(T.unsafe(nil), ImageSize::ISOBMFF)

# source://image_size//lib/image_size/isobmff.rb#8
class ImageSize::ISOBMFF
  # @return [ISOBMFF] a new instance of ISOBMFF
  #
  # source://image_size//lib/image_size/isobmff.rb#41
  def initialize(options = T.unsafe(nil)); end

  # source://image_size//lib/image_size/isobmff.rb#91
  def recurse(reader, offset = T.unsafe(nil), length = T.unsafe(nil), &block); end

  # source://image_size//lib/image_size/isobmff.rb#47
  def walk(reader, offset = T.unsafe(nil), length = T.unsafe(nil)); end
end

# source://image_size//lib/image_size/isobmff.rb#9
class ImageSize::ISOBMFF::Box
  # @return [Box] a new instance of Box
  #
  # source://image_size//lib/image_size/isobmff.rb#12
  def initialize(attributes); end

  # source://image_size//lib/image_size/isobmff.rb#20
  def data_offset; end

  # source://image_size//lib/image_size/isobmff.rb#24
  def data_size; end

  # Returns the value of attribute index.
  #
  # source://image_size//lib/image_size/isobmff.rb#10
  def index; end

  # Returns the value of attribute offset.
  #
  # source://image_size//lib/image_size/isobmff.rb#10
  def offset; end

  # Returns the value of attribute relative_data_offset.
  #
  # source://image_size//lib/image_size/isobmff.rb#10
  def relative_data_offset; end

  # Returns the value of attribute size.
  #
  # source://image_size//lib/image_size/isobmff.rb#10
  def size; end

  # Returns the value of attribute type.
  #
  # source://image_size//lib/image_size/isobmff.rb#10
  def type; end
end

# source://image_size//lib/image_size/isobmff.rb#29
class ImageSize::ISOBMFF::FullBox < ::ImageSize::ISOBMFF::Box
  # @return [FullBox] a new instance of FullBox
  #
  # source://image_size//lib/image_size/isobmff.rb#32
  def initialize(attributes); end

  # Returns the value of attribute flags.
  #
  # source://image_size//lib/image_size/isobmff.rb#30
  def flags; end

  # Returns the value of attribute version.
  #
  # source://image_size//lib/image_size/isobmff.rb#30
  def version; end
end

# source://image_size//lib/image_size/isobmff.rb#39
ImageSize::ISOBMFF::S64_OVERFLOW = T.let(T.unsafe(nil), Integer)

# source://image_size//lib/image_size.rb#341
ImageSize::JP2_WALKER = T.let(T.unsafe(nil), ImageSize::ISOBMFF)

# source://image_size//lib/image_size.rb#158
ImageSize::JPEG_CODE_CHECK = T.let(T.unsafe(nil), Array)

# source://image_size//lib/image_size/reader.rb#7
module ImageSize::Reader
  # source://image_size//lib/image_size/reader.rb#53
  def fetch(offset, length); end

  # source://image_size//lib/image_size/reader.rb#77
  def stream(offset); end

  # source://image_size//lib/image_size/reader.rb#63
  def unpack(offset, length, format); end

  # source://image_size//lib/image_size/reader.rb#68
  def unpack1(offset, length, format); end

  class << self
    # source://image_size//lib/image_size/reader.rb#22
    def open(input); end

    private

    # source://image_size//lib/image_size/reader.rb#39
    def for_io(io); end
  end
end

# source://image_size//lib/image_size/reader.rb#8
class ImageSize::Reader::Stream
  # @return [Stream] a new instance of Stream
  #
  # source://image_size//lib/image_size/reader.rb#9
  def initialize(reader, offset); end

  # source://image_size//lib/image_size/reader.rb#14
  def unpack1(length, format); end
end

# source://image_size//lib/image_size.rb#74
ImageSize::SVG_R = T.let(T.unsafe(nil), Regexp)

# source://image_size//lib/image_size/seekable_io_reader.rb#6
class ImageSize::SeekableIOReader
  include ::ImageSize::Reader
  include ::ImageSize::ChunkyReader

  # @return [SeekableIOReader] a new instance of SeekableIOReader
  #
  # source://image_size//lib/image_size/seekable_io_reader.rb#9
  def initialize(io); end

  private

  # source://image_size//lib/image_size/seekable_io_reader.rb#17
  def chunk(i); end
end

# Array joining with 'x'
#
# source://image_size//lib/image_size.rb#14
class ImageSize::Size < ::Array
  # get second element
  #
  # source://image_size//lib/image_size.rb#27
  def h; end

  # get second element
  #
  # source://image_size//lib/image_size.rb#27
  def height; end

  # join using 'x'
  #
  # source://image_size//lib/image_size.rb#16
  def to_s; end

  # get first element
  #
  # source://image_size//lib/image_size.rb#21
  def w; end

  # get first element
  #
  # source://image_size//lib/image_size.rb#21
  def width; end
end

# source://image_size//lib/image_size/stream_io_reader.rb#6
class ImageSize::StreamIOReader
  include ::ImageSize::Reader
  include ::ImageSize::ChunkyReader

  # @return [StreamIOReader] a new instance of StreamIOReader
  #
  # source://image_size//lib/image_size/stream_io_reader.rb#9
  def initialize(io); end

  private

  # source://image_size//lib/image_size/stream_io_reader.rb#16
  def chunk(i); end
end

# source://image_size//lib/image_size/string_reader.rb#6
class ImageSize::StringReader
  include ::ImageSize::Reader

  # @return [StringReader] a new instance of StringReader
  #
  # source://image_size//lib/image_size/string_reader.rb#9
  def initialize(string); end

  # source://image_size//lib/image_size/string_reader.rb#17
  def [](offset, length); end
end

# source://image_size//lib/image_size.rb#75
ImageSize::XML_R = T.let(T.unsafe(nil), Regexp)
