# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mini_suffix` gem.
# Please instead update this file by running `bin/tapioca gem mini_suffix`.

# source://mini_suffix//lib/mini_suffix/version.rb#1
module MiniSuffix
  extend ::FFI::Library

  def psl_builtin(*_arg0); end
  def psl_get_version(*_arg0); end
  def psl_registrable_domain(*_arg0); end

  class << self
    # Extracts the shortest private suffix part of the hostname
    #
    # @param hostname [String]
    # @return [String] private_suffix
    #
    # source://mini_suffix//lib/mini_suffix.rb#25
    def domain(hostname); end

    def psl_builtin(*_arg0); end
    def psl_get_version(*_arg0); end
    def psl_registrable_domain(*_arg0); end
  end
end

# source://mini_suffix//lib/mini_suffix/version.rb#2
MiniSuffix::VERSION = T.let(T.unsafe(nil), String)
