# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rack-mini-profiler` gem.
# Please instead update this file by running `bin/tapioca gem rack-mini-profiler`.

# based off https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/instrumentation/active_record.rb
# fallback for alls sorts of weird dbs
#
# source://rack-mini-profiler//lib/enable_rails_patches.rb#3
module Rack
  class << self
    # source://rack/2.2.8/lib/rack/version.rb#26
    def release; end

    # source://rack/2.2.8/lib/rack/version.rb#19
    def version; end
  end
end

# source://rack-mini-profiler//lib/enable_rails_patches.rb#4
Rack::MINI_PROFILER_ENABLE_RAILS_PATCHES = T.let(T.unsafe(nil), TrueClass)
