# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rbtrace` gem.
# Please instead update this file by running `bin/tapioca gem rbtrace`.

module FFI::LastError
  private

  def error; end
  def error=(_arg0); end

  class << self
    def error; end
    def error=(_arg0); end
  end
end
