# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rtlcss` gem.
# Please instead update this file by running `bin/tapioca gem rtlcss`.

# source://rtlcss//lib/rtlcss/version.rb#3
module Rtlcss
  class << self
    # source://rtlcss//lib/rtlcss.rb#9
    def flip_css(orig_css); end
  end
end

# source://rtlcss//lib/rtlcss.rb#7
class Rtlcss::FlipError < ::StandardError; end

# source://rtlcss//lib/rtlcss/version.rb#4
Rtlcss::VERSION = T.let(T.unsafe(nil), String)
