# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yaml-lint` gem.
# Please instead update this file by running `bin/tapioca gem yaml-lint`.

# source://yaml-lint//lib/yaml-lint.rb#5
module Logging
  # source://yaml-lint//lib/yaml-lint.rb#23
  def emit(opts = T.unsafe(nil)); end

  # source://yaml-lint//lib/yaml-lint.rb#19
  def error(message); end

  # source://yaml-lint//lib/yaml-lint.rb#11
  def info(message); end

  # source://yaml-lint//lib/yaml-lint.rb#15
  def warn(message); end
end

# source://yaml-lint//lib/yaml-lint.rb#6
Logging::ESCAPES = T.let(T.unsafe(nil), Hash)

# source://yaml-lint//lib/yaml-lint.rb#33
class YamlLint
  include ::Logging

  # @return [YamlLint] a new instance of YamlLint
  #
  # source://yaml-lint//lib/yaml-lint.rb#36
  def initialize(file, config = T.unsafe(nil)); end

  # source://yaml-lint//lib/yaml-lint.rb#43
  def do_lint; end

  # source://yaml-lint//lib/yaml-lint.rb#57
  def parse_directory(directory); end

  # source://yaml-lint//lib/yaml-lint.rb#68
  def parse_file(file); end

  private

  # source://yaml-lint//lib/yaml-lint.rb#96
  def format_directory(directory); end
end
